# Generated by Django 3.2.5 on 2021-07-14 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empNo', models.CharField(max_length=100)),
                ('empName', models.CharField(max_length=100)),
                ('empMobile', models.CharField(max_length=100)),
                ('empEmail', models.EmailField(max_length=254)),
            ],
        ),
    ]
