# Generated by Django 3.2.5 on 2021-07-15 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fbvApp', '0003_auto_20210715_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='empSal',
            field=models.IntegerField(),
        ),
    ]
