# Generated by Django 3.2.5 on 2021-07-18 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('decription', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to='product\\images')),
                ('Category_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectApp.category')),
            ],
        ),
        migrations.DeleteModel(
            name='SignUp',
        ),
    ]
