# Generated by Django 3.2.5 on 2021-07-21 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoffeeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coffee_name', models.CharField(max_length=50)),
                ('hot', models.CharField(max_length=50)),
                ('iced', models.CharField(max_length=50)),
                ('blended', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SnacksModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snacks_name', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TeaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tea_name', models.CharField(max_length=50)),
                ('hot', models.CharField(max_length=50)),
                ('iced', models.CharField(max_length=50)),
                ('addon', models.CharField(max_length=50)),
            ],
        ),
    ]
